### PR TITLE
fix: changed maxlength groupname to 45 char

### LINKED ISSUE #276: Groupname should be only allowed up to 45 characters, because hashed groupname becomes too long for database
Related to the BUG https://github.com/corona-warn-app/cwa-quick-test-backend/issues/212 we found out that "Patientendaten erfassen" failes with 500 when groupname is longer than 45 characters. Then the hashed groupname becomes to long for the database and this failes with "Couldn't create quicktest. Groupname value is too long"

So the quick fix for that issue will be to set a minimum of allowed characters in groupname og 47 characters instead of 50.

### PR DESCRIPTION
**Pull request by kerstin-oppermann-tsi**

### CODE REVIEW

**Comment by Ein-Tim** [comment]
What influence will this change have to testing sites which are currently using a groupname between 45-50 characters? Will they see a helpful error message which explains what the problem is or will they suddenly see an error?

**Comment by ascheibal** [comment]
> Hi @Ein-Tim ,
Teststellen with more than 45 Char cannot create tests - as their Teststellenname is stored encrypted in the datase, it exceeds the column size otherwise (currently 100 characters) due to the encryption.
The Teststellenbetreiber will recognize this the first time they create a test  - and probably will not pin it to the long name, the Teststelle is given.

**Review by ascheibal — DISMISSED** [review]

**Comment by Ein-Tim** [comment]
@ascheibal 

> The Teststellenbetreiber will recognize this the first time they create a test - and probably will not pin it to the long name, the Teststelle is given.

Okay, wouldn't it make sense to show a hint to them to help them to mitigate the issue?

**Comment by kerstin-oppermann-tsi** [comment]
image
This is the hint they will get.

**Comment by Ein-Tim** [comment]
@kerstin-oppermann-tsi Okay thanks, sorry for the questions 😅

**Review by ascheibal — APPROVED** [review]

**Pull request merged**
