### PR TITLE
feat: icao

### LINKED ISSUE #185: feat: prefill ICAO fields.
## Feature description

The standardized name fields are neccessary for DCC conformity.

## Problem and motivation
documentation: [9303_p3_cons_en.pdf](https://github.com/corona-warn-app/cwa-quick-test-frontend/files/6607283/9303_p3_cons_en.pdf)

example implementation in python for substitution:
https://github.com/Arg0s1080/mrz/blob/master/mrz/generator/dictionaries/latin_based.py

### LINKED ISSUE #285: remove ICAO input fields
As discussed in #185 converting to ICAO by hand results in errors and problems in CWA matching certificates.

I would like to suggest to remove the input fields from UI after the auto-conversion is merged and tested.

### PR DESCRIPTION
**Pull request by ggrund-tsi**

### CODE REVIEW

**Review by fOppenheimer — APPROVED** [review]
reviewed

**Comment by janhoffmann** [comment]
@fOppenheimer any progress on this?

**Comment by fOppenheimer** [comment]
Hello @janhoffmann,
we can't decide it ourselves, we have to wait for some customer decisions.

**Comment by Ein-Tim** [comment]
@fOppenheimer 

"Customer" = RKI/BMG 
or 
"Customer" = Testing stations

?

**Comment by fOppenheimer** [comment]
"Customer" = RKI/BMG

**Comment by janhoffmann** [comment]
@fOppenheimer any progress on this?

**Review by kerstin-oppermann-tsi — APPROVED** [review]

**Pull request merged**
